apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: beegfs
    tier: monitor
  name: beegfs
  namespace: default
spec:
  selector:
    matchLabels:
      name: beegfs
  template:
    metadata:
      labels:
        name: beegfs
      name: beegfs-pod
    spec:
      containers:
      - image: docker.io/brtknr/beegfs-client:7
        imagePullPolicy: IfNotPresent
        name: beegfs-test
        env:
        - name: BEEGFS_MGMTD_HOST
          value: 10.60.253.20
        volumeMounts:
        - mountPath: /mnt/beegfs
          name: beegfs-pv-volume
          mountPropagation: Bidirectional
        securityContext:
          privileged: true
      hostNetwork: true
      volumes:
      - name: beegfs-pv-volume
        persistentVolumeClaim:
          claimName: beegfs-pv-claim
